export const FETCH_TOTAL_DATA_REQUEST = 'DYNAMICVIEW/FETCH_TOTAL_DATA_REQUEST';
export const FETCH_TOTAL_DATA_SUCCEED = 'DYNAMICVIEW/FETCH_TOTAL_DATA_SUCCEED';
export const FETCH_TOTAL_DATA_FAILURE = 'DYNAMICVIEW/FETCH_TOTAL_DATA_FAILURE';

export const FETCH_BUS_REALTIME_POSITIONS_REQUEST = 'DYNAMICVIEW/FETCH_BUS_REALTIME_POSITIONS_REQUEST';
export const FETCH_BUS_REALTIME_POSITIONS_SUCCEED = 'DYNAMICVIEW/FETCH_BUS_REALTIME_POSITIONS_SUCCEED';
export const FETCH_BUS_REALTIME_POSITIONS_FAILURE = 'DYNAMICVIEW/FETCH_BUS_REALTIME_POSITIONS_FAILURE';

export const FETCH_BUS_REALTIME_INFO_REQUEST = 'DYNAMICVIEW/FETCH_BUS_REALTIME_INFO_REQUEST';
export const FETCH_BUS_REALTIME_INFO_SUCCEED = 'DYNAMICVIEW/FETCH_BUS_REALTIME_INFO_SUCCEED';
export const FETCH_BUS_REALTIME_INFO_FAILURE = 'DYNAMICVIEW/FETCH_BUS_REALTIME_INFO_FAILURE';

export const FETCH_TRAFFIC_RANK_REQUEST = 'DYNAMICVIEW/FETCH_TRAFFIC_RANK_REQUEST';
export const FETCH_TRAFFIC_RANK_SUCCEED = 'DYNAMICVIEW/FETCH_TRAFFIC_RANK_SUCCEED';
export const FETCH_TRAFFIC_RANK_FAILURE = 'DYNAMICVIEW/FETCH_TRAFFIC_RANK_FAILURE';

export const FETCH_COVERAGE_REQUEST = 'DYNAMICVIEW/FETCH_COVERAGE_REQUEST';
export const FETCH_COVERAGE_SUCCEED = 'DYNAMICVIEW/FETCH_COVERAGE_SUCCEED';
export const FETCH_COVERAGE_FAILURE = 'DYNAMICVIEW/FETCH_COVERAGE_FAILURE';

export const FETCH_PUBLIC_TRANSPORT_INFO_REQUEST = 'DYNAMICVIEW/FETCH_PUBLIC_TRANSPORT_INFO_REQUEST';
export const FETCH_PUBLIC_TRANSPORT_INFO_SUCCEED = 'DYNAMICVIEW/FETCH_PUBLIC_TRANSPORT_INFO_SUCCEED';
export const FETCH_PUBLIC_TRANSPORT_INFO_FAILURE = 'DYNAMICVIEW/FETCH_PUBLIC_TRANSPORT_INFO_FAILURE';

export const FETCH_SEARCH_BUS_LINE_REQUEST = 'DYNAMICVIEW/FETCH_SEARCH_BUS_LINE_REQUEST';
export const FETCH_SEARCH_BUS_LINE_SUCCEED = 'DYNAMICVIEW/FETCH_SEARCH_BUS_LINE_SUCCEED';
export const FETCH_SEARCH_BUS_LINE_FAILURE = 'DYNAMICVIEW/FETCH_SEARCH_BUS_LINE_FAILURE';

export const FETCH_TRAFFIC_EVENT_REQUEST = 'DYNAMICVIEW/FETCH_TRAFFIC_EVENT_REQUEST';
export const FETCH_TRAFFIC_EVENT_SUCCEED = 'DYNAMICVIEW/FETCH_TRAFFIC_EVENT_SUCCEED';
export const FETCH_TRAFFIC_EVENT_FAILURE = 'DYNAMICVIEW/FETCH_TRAFFIC_EVENT_FAILURE';

export const FETCH_TRAFFIC_JAM_LINE_REQUEST = 'DYNAMICVIEW/FETCH_TRAFFIC_JAM_LINE_REQUEST';
export const FETCH_TRAFFIC_JAM_LINE_SUCCEED = 'DYNAMICVIEW/FETCH_TRAFFIC_JAM_LINE_SUCCEED';
export const FETCH_TRAFFIC_JAM_LINE_FAILURE = 'DYNAMICVIEW/FETCH_TRAFFIC_JAM_LINE_FAILURE';
